network:
  version: 2
  ethernets:
    enp1s0f0np0:
      dhcp4: false
      optional: true
      addresses: [10.10.4.1/24]
      routes:
        - to: 10.10.2.2/32
          via: 10.10.4.2
    enP2p1s0f0np0:
      dhcp4: false
      optional: true
      addresses: [10.10.5.1/24]
    enp1s0f1np1:
      dhcp4: false
      optional: true
      addresses: [10.10.0.2/24]
    enP2p1s0f1np1:
      dhcp4: false
      optional: true
      addresses: [10.10.1.2/24]
